### ISSUE TITLE
Bot stops outputting to discord after failed vote

### ISSUE THREAD

**Issue by LordTylus** [FabioZumbi12/SEDiscordBridge#46]
Hello there,

we have a voting feature for restarts on our server which uses the voting system provided by the Essentials plugin. 

However even if the vote ends the bot seems to be only half functional.

QuackDuck: ok
Helios: beast send pics of your base tho
Server: Voting for restart ends in 10 seconds.
Server: Voting for restart ends in 9 seconds.
Server: Voting for restart ends in 8 seconds.
Server: Voting for restart ends in 7 seconds.
Server: Voting for restart ends in 6 seconds.
Server: BEAST was killed by an admin
Server: Voting for restart ends in 5 seconds.
(no further outputs after that)

The server did not restart though as the vote failed. Status messages still work and Discord to Ingame chat also works

But Ingame to Discord wont work anymore. 

Not sure if it is actually related but my players keep telling me that this happens quite often after a failed vote.

**Comment by LordTylus** [comment]
Maybe discord changed something on their side and those messages were too many for the bot. 

so instead of just crashing the server maybe it just stops outputting all together 🤷‍♂

**Comment by jokerman89** [comment]
We have the same issue but it is not tied to voting it happens when we send out "Server restarting in X seconds".. The Torch Essentials !restart command..

Server: Restarting server in 10 seconds.
Server: Restarting server in 9 seconds.
Server: Restarting server in 8 seconds.
Server: Restarting server in 7 seconds.
Server: Restarting server in 6 seconds.
(No more output)
Server Started!
(No more output after restart, only reloading the plugin works).

Discord to ingame works, player joins, leaves works but ingame chat to discord stops working entirely.

**Comment by Rahonbass** [comment]
Discord to SE bridge is not properly keeping track of messages. When people try to chat into the server the name in not carrying over and shows up as nothing. Also the chat log is way behind real time.

**Comment by FabioZumbi12** [comment]
SEDB is now maintained by Bishbash777 on https://github.com/Bishbash777/SEDB-RELOADED
